//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica_DanielGarita_CNET.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int idCita { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public Nullable<int> idDoctor { get; set; }
        public Nullable<int> idTratamiento { get; set; }
        public string descripcionCita { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Doctores Doctores { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        public virtual Tratamientos Tratamientos { get; set; }
    }
}
